{% set version = "0.3.0" %}

package:
  name: cargo-license
  version: {{ version }}

source:
  url: https://github.com/onur/cargo-license/archive/v{{ version }}.tar.gz
  sha256: 50edb76242a93604386deb87f730d08538f893a571cd1ae6a3f53dd203c7bfae

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  run:
    - rust

test:
  commands:
    - cargo-license --help

about:
  home: https://github.com/onur/cargo-license/
  summary: Cargo subcommand to see license of dependencies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
