{% set name = "cryptsetup" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.kernel.org/pub/linux/utils/cryptsetup/v{{ '.'.join(version.split('.')[:-1]) }}/cryptsetup-{{ version }}.tar.xz
  sha256: 2af0ec9551ab9c870074cae9d3f68d82cab004f4095fa89db0e4413713424a46

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=cryptsetup
    - {{ pin_subpackage('cryptsetup', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/lib/libgl2ps$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_LIB%\\libgl2ps.dll exit 1  # [win]

about:
  home: https://gitlab.com/cryptsetup/cryptsetup/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LGPL
  summary: 'Cryptsetup and LUKS - open-source disk encryption'
  description: |
    Cryptsetup is a utility used to conveniently set up disk encryption based
    on the DMCrypt kernel module.

    These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt
    (including VeraCrypt extension) formats.

    The project also includes a veritysetup utility used to conveniently setup
    DMVerity block integrity checking kernel module and, since version 2.0,
    integritysetup to setup DMIntegrity block integrity kernel module.
  doc_url: http://geuz.org/gl2ps/#tth_sEc1
  dev_url: https://gitlab.com/cryptsetup/cryptsetup/

extra:
  recipe-maintainers:
    - chrisburr
