{% set name = "ca-policy-egi-core" %}
{% set version = "1.96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://repository.egi.eu/sw/production/cas/1/current/meta/LICENSE
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f

build:
  noarch: generic
  number: 0

requirements:
  build:
    - curl
    - sed
  run:
    - python
    - setuptools

test:
  commands:
    - ${PREFIX}/share/grid-security/check_for_updates.py --debug

about:
  home: http://github.com/simplejson/simplejson
  # The license is a mixture of CC-BY-3.0 and MPL 1.1, see the file for details
  license: CUSTOM
  license_file: LICENSE
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <http://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  doc_url: http://simplejson.readthedocs.io/
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - chrisburr
