{% set version = "0.2.64" %}

package:
  name: ffsend
  version: {{ version }}

source:
  url: https://github.com/timvisee/ffsend/archive/v{{ version }}.tar.gz
  sha256: bb4c435e864cd543075b3a35a9d6af62d51c7a1a1859e381518da0a52c073e99

build:
  number: 0
  missing_dso_whitelist:
    - '*/x86_64-conda-linux-gnu/sysroot/lib64/*'  # [linux]
    - '/usr/lib/libresolv.9.dylib'  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - openssl

test:
  commands:
    - echo This is a test> test.txt
    - ffsend upload test.txt

about:
  home: https://github.com/timvisee/ffsend/
  summary: Easily and securely share files from the command line. A fully featured Firefox Send client.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
