{% set name = "device-mapper" %}
{% set version = "2.03.07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://mirrors.kernel.org/sourceware/lvm2/LVM2.{{ version }}.tgz
  sha256: c72f1095c82ca884c0f46c003a0da9b60b68554a8c913ca6c29d01fae04301e9

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=cryptsetup
    - {{ pin_subpackage('device-mapper', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libuuid

# test:
#   commands:
#     - test -f $PREFIX/lib/libgl2ps$SHLIB_EXT  # [unix]
#     - if not exist %LIBRARY_LIB%\\libgl2ps.dll exit 1  # [win]

about:
  home: http://sourceware.org/dm/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING.LGPL
  summary: 'Cryptsetup and LUKS - open-source disk encryption'
  description: |
    Cryptsetup is a utility used to conveniently set up disk encryption based
    on the DMCrypt kernel module.

    These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt
    (including VeraCrypt extension) formats.

    The project also includes a veritysetup utility used to conveniently setup
    DMVerity block integrity checking kernel module and, since version 2.0,
    integritysetup to setup DMIntegrity block integrity kernel module.
  doc_url: http://geuz.org/gl2ps/#tth_sEc1
  dev_url: https://gitlab.com/cryptsetup/cryptsetup/

extra:
  recipe-maintainers:
    - chrisburr
