{% set name = "scikit-hep" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-hep-{{ version }}.tar.gz
  sha256: 62f1d971ae899df05e364b80d5a50df323e58d1b0d60e9ebeaa0e9fe0b32dbe4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - awkward ~=0.12
    - boost-histogram ~=0.11.0
    - decaylanguage ~=0.8.0
    - hepunits ~=2.0.0
    - hist ~=2.0.0
    - iminuit ~=1.5.0
    - matplotlib-base >2.0.0
    - mplhep ~=0.2.0
    - numpy >=1.13.1
    - particle ~=0.12.0
    - uproot ~=3.12.0
    - uproot-methods ~=0.7.0

test:
  imports:
    - skhep
    - skhep.dataset
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/scikit-hep/
  summary: Toolset of interfaces and tools for Particle Physics.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - eduardo-rodrigues
